### ISSUE TITLE
Material Component Theme 이슈

### ISSUE THREAD

**Issue by Hooooong** [PRNDcompany/YouTubePlayerView#10]
라이브러리를 사용중에 이슈가 있어 문의드립니다.

App Theme를 `Theme.AppCompat.Light.DarkActionBar`에서 `Theme.MaterialComponents.Light.NoActionBar` 로 변경할 경우 Youtube Player 의 실행은 정상동작하지만 화질을 변경할 경우에 앱이 종료되는 이슈가 있었습니다.

확인 한번 부탁드립니다.

**Comment by ted-prnd** [comment]
@Hooooong 
에러 로그를 공유해주실 수 있나요?
샘플 프로젝트에서 style을 `Theme.MaterialComponents.Light.NoActionBar`로 변경하고 화질을 변경해도 오류가 발생하지 않습니다

**Comment by Hooooong** [comment]
@ted-prnd 
`
com.example.youtubeplayerview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.youtubeplayerview, PID: 25178
    android.view.InflateException: Binary XML file line #80 in android:layout/alert_dialog_material: Binary XML file line #37 in android:layout/alert_dialog_button_bar_material: Error inflating class Button
    Caused by: android.view.InflateException: Binary XML file line #37 in android:layout/alert_dialog_button_bar_material: Error inflating class Button
    Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:200)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:191)
        at com.google.android.material.theme.MaterialComponentsViewInflater.createButton(MaterialComponentsViewInflater.java:60)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:111)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:242)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:438)
        at com.android.internal.app.AlertController.installContent(AlertController.java:271)
        at android.app.AlertDialog.onCreate(AlertDialog.java:439)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
        at android.app.Dialog.show(Dialog.java:315)
        at com.google.android.apps.youtube.embeddedplayer.service.jar.EmbedOverflowOverlay.onClick(SourceFile:97)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

실 기기에서는 오류가 발생하지는 않는데, 에뮬레이터에서는 화질을 변경할 때 오류가 발생하는 것 같습니다.
